In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

file_path = '/content/drive/MyDrive/IBM NEXT BEST SOLUTION/Sales 2016-2022 v6.xlsx'
sales_data = pd.read_excel(file_path)

In [ ]:
# Display the first few rows of the dataframe
sales_data.head()

,ZXG ID,Country,Industry,UT L30 - Segment,Family,Product name,PA part description,Rev type,20161,20162,...,20204,20211,20212,20213,20214,20221,20222,20223,20224,Grand Total
0,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,B2B INTEGRATOR AO GLOBAL HIGH AVAILABILITY MB ...,Transaction,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2503116.9
1,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,B2B INTEGRATOR AO GLOBAL HIGH AVAILABILITY MB ...,Subs & Supp,NaN,NaN,...,31322.7,31322.7,31322.7,31322.7,31322.7,31322.7,31322.7,31322.7,31322.7,407055.6
2,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,B2B INTEGRATOR AO GLOBAL HIGH AVAILABILITY MB ...,Subs & Supp,NaN,NaN,...,125298.9,125298.9,125298.9,125298.9,125298.9,125298.9,125298.9,125298.9,125298.9,1628306.1
3,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,STERLING B2B INTEGRATOR ENT ED PVU SUPT,Subs & Supp,2797.2,2797.2,...,22226.4,22226.4,22226.4,22307.4,22307.4,22307.4,22307.4,22307.4,22307.4,278391.6
4,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,STERLING B2B INTEGRATOR ENT ED PVU SUB,Subs & Supp,11188.8,11188.8,...,88911.0,88911.0,88911.0,89237.7,89237.7,89237.7,89237.7,89237.7,89237.7,1113647.4

In [ ]:
# Columns to replace NaN values
cols_to_replace = ['20161','20162','20163','20164','20171','20172','20173','20174','20181','20182','20183','20184','20191','20192','20193','20194','20201','20202','20203','20204','20211','20212','20213','20214','20221','20222','20223','20224', 'Grand Total']

# Convert column names to strings
sales_data.columns = sales_data.columns.astype(str)

# Replace NaN values with 0 in the specified columns
sales_data[cols_to_replace] = sales_data[cols_to_replace].fillna(0)

# Replace negative values with 0 in the specified columns
sales_data[cols_to_replace] = sales_data[cols_to_replace].applymap(lambda x: max(0, x))

In [ ]:
# Display the first few rows of the DataFrame after replacing NaN values
sales_data.head()

,ZXG ID,Country,Industry,UT L30 - Segment,Family,Product name,PA part description,Rev type,20161,20162,...,20204,20211,20212,20213,20214,20221,20222,20223,20224,Grand Total
0,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,B2B INTEGRATOR AO GLOBAL HIGH AVAILABILITY MB ...,Transaction,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2503116.9
1,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,B2B INTEGRATOR AO GLOBAL HIGH AVAILABILITY MB ...,Subs & Supp,0.0,0.0,...,31322.7,31322.7,31322.7,31322.7,31322.7,31322.7,31322.7,31322.7,31322.7,407055.6
2,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,B2B INTEGRATOR AO GLOBAL HIGH AVAILABILITY MB ...,Subs & Supp,0.0,0.0,...,125298.9,125298.9,125298.9,125298.9,125298.9,125298.9,125298.9,125298.9,125298.9,1628306.1
3,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,STERLING B2B INTEGRATOR ENT ED PVU SUPT,Subs & Supp,2797.2,2797.2,...,22226.4,22226.4,22226.4,22307.4,22307.4,22307.4,22307.4,22307.4,22307.4,278391.6
4,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,STERLING B2B INTEGRATOR ENT ED PVU SUB,Subs & Supp,11188.8,11188.8,...,88911.0,88911.0,88911.0,89237.7,89237.7,89237.7,89237.7,89237.7,89237.7,1113647.4

In [ ]:
from itertools import groupby
from operator import itemgetter

# Find the indices of the rows where 'ZXG ID' is blank
blank_indices = sales_data[sales_data['ZXG ID'].isna()].index.tolist()

# Function to convert list of indices to ranges
def indices_to_ranges(indices):
    """Convert a list of indices to ranges"""
    ranges = []
    for k, g in groupby(enumerate(indices), lambda i_x:i_x[0]-i_x[1]):
        consecutive_indices = list(map(itemgetter(1), g))
        if len(consecutive_indices) == 1:
            ranges.append(str(consecutive_indices[0]))
        else:
            ranges.append(f"{consecutive_indices[0]}-{consecutive_indices[-1]}")
    return ranges

# Convert indices to ranges
blank_ranges = indices_to_ranges(blank_indices)
blank_ranges

['5780-5983',
 '6934-7079',
 '14962-15053',
 '20712-20777',
 '20829-20894',
 '29617-29703',
 '32024-32037',
 '32457-32518',
 '34181-34244',
 '34336-34351',
 '35441-35469',
 '38015-38023',
 '38828-38863',
 '41792-41806',
 '45231-45242',
 '46720-46731',
 '47870-47892',
 '48807',
 '48845-48848',
 '49455-49460',
 '49750-49753',
 '50679-50682',
 '51716-51723',
 '51988-51989',
 '52631-52632',
 '53124-53131',
 '53478-53483',
 '53926-53927',
 '54800-54802',
 '54981-54986',
 '55271-55273',
 '55825-55833',
 '56040-56041',
 '56220-56234',
 '56259-56264',
 '57101-57106',
 '57619-57622',
 '57712-57718',
 '57978-57980',
 '58080-58084',
 '58099-58102',
 '58465-58468',
 '58534-58535',
 '59603-59612',
 '59629-59662',
 '59679-59682',
 '59796-59804',
 '59837-59841',
 '59861-59863',
 '59921-59926',
 '60635-60680',
 '60829-60843',
 '62275-62294',
 '62346-62404',
 '64314-64329',
 '65835-65845',
 '66261-66275',
 '68672-68682',
 '68894-68913',
 '69538-69546',
 '70467-70472',
 '70596-70624',
 '70767-70779',
 '71050-71056',
 '72543-72550',
 '73835-73840',
 '75724-75726',
 '75811-75818',
 '76582-76584',
 '77866-77867',
 '77980-77981',
 '78038-78039',
 '78418-78419',
 '78813-78814',
 '79455-79463',
 '79799-79804',
 '80011-80013',
 '80158',
 '80595',
 '80856',
 '81121-81122',
 '81356',
 '81889',
 '81986-81987',
 '82080-82081',
 '82150-82153',
 '82176',
 '82692',
 '82859-82865',
 '82883',
 '83105',
 '83594-83596',
 '84058-84059',
 '84330-84331',
 '84823-84826',
 '84960-84962',
 '85465-85466',
 '86396',
 '87608-87609',
 '88323',
 '89192-89194',
 '89222-89226',
 '89240',
 '89345-89346',
 '89348',
 '89362-89364',
 '89375-89379',
 '89474-89495',
 '89529-89538']

In [ ]:
# Find all the rows where 'Country' is blank
blank_rows_country = sales_data[sales_data['Country'].isna()].index.tolist()

# Apply function to get ranges
blank_ranges_country = indices_to_ranges(blank_rows_country)
blank_ranges_country

['6934-7079', '62275-62294']

In [ ]:
# Replace the blanks in the specified ranges with the specified values
sales_data.loc[6934:7079, 'Country'] = sales_data.loc[6934:7079, 'Country'].fillna('Moe_Country')
sales_data.loc[62275:62294, 'Country'] = sales_data.loc[62275:62294, 'Country'].fillna('Wanchi_Country')

# Check if the replacements were successful
sales_data.loc[6934:7079]['Country'].unique(), sales_data.loc[62275:62294]['Country'].unique()

(array(['Moe_Country'], dtype=object), array(['Wanchi_Country'], dtype=object))

In [ ]:
# Initialize a company counter
company_counter = 1

# Iterate over the blank ranges in the 'ZXG ID' column
for start, end in [(int(r.split('-')[0]), int(r.split('-')[1])) if '-' in r else (int(r), int(r)) for r in blank_ranges]:
    # Get the unique countries in the current range
    unique_countries = sales_data.loc[start:end, 'Country'].unique()

    # Iterate over the unique countries
    for country in unique_countries:
        # Get the indices for the current country within the current range
        #indices = sales_data.loc[start:end][sales_data['Country'] == country].index
        indices = sales_data.loc[start:end][sales_data.loc[start:end, 'Country'] == country].index

        # Assign the company name to the 'ZXG ID' column for the current indices
        sales_data.loc[indices, 'ZXG ID'] = f'MW{company_counter}'

        # Increment the company counter
        company_counter += 1

# Check the first few rows of the modified dataset
sales_data.loc[[5780,5983,6934,7079,14962,15053,59837,59838,59839,59840,59841], :]

,ZXG ID,Country,Industry,UT L30 - Segment,Family,Product name,PA part description,Rev type,20161,20162,...,20204,20211,20212,20213,20214,20221,20222,20223,20224,Grand Total
5780,MW1,United States,NaN,Sterling Transformation Extender,STER TRANSX,WebSphere Transform Ext Com Svr,WEBSPHERE TRANSFORM EXTEND WITH COMMAND PVU INSTL,Transaction,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1395744.3
5983,MW1,United States,NaN,Sterling Partner Engagement Manager,PEM,Sterling Prtnr Engage Mgr Software,IBM STERL PRTNR ENGAGEMENT MGR STD CTNR ED RVU...,Transaction,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,23102.1,0.0,0.0,0.0,23102.1
6934,MW2,Moe_Country,NaN,Sterling Transformation Extender,STER TRANSX,WS Transfrm Ext Pk Design Studio,WEBSPHERE TRANSFORM EXTENDER DESIGN STU AUTHUS...,Subs & Supp,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7079,MW2,Moe_Country,NaN,Sterling Partner Engagement Manager,PEM,Sterling Prtnr Engage Mgr Software,IBM STERLING PARTNER ENG MNGR STD ED PER ENTIT...,Transaction,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14962,MW3,Germany,NaN,Sterling Managed File Transfer,STER MFT,MFT Connect:Direct,STERLING C D STD ED NON-PROD ENV SMLT SESSN SUPT,Subs & Supp,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,115.2
15053,MW3,Germany,NaN,Sterling Partner Engagement Manager,PEM,Sterling Prtnr Engage Mgr Software,IBM STERL PRTNR ENGAGEMENT MGR STD CTNR ED RVU...,Transaction,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
59837,MW48,Denmark,NaN,Sterling Managed File Transfer,STER MFT,MFT Connect:Direct,STERLING C D PREM ED PVU SUPT,Subs & Supp,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
59838,MW49,Czech Republic,NaN,Sterling Managed File Transfer,STER MFT,MFT Connect:Direct,STERLING C D STD ED NON-PROD ENV SMLT SESSN SUPT,Subs & Supp,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
59839,MW49,Czech Republic,NaN,Sterling Managed File Transfer,STER MFT,MFT Connect:Direct,STERLING C D STD ED SMLT SESSN SUPT,Subs & Supp,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
59840,MW50,Belarus,NaN,Sterling Managed File Transfer,STER MFT,MFT Connect:Direct,STERLING C D STD ED NON-PROD ENV SMLT SESSN SUPT,Subs & Supp,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
59841,MW50,Belarus,NaN,Sterling Managed File Transfer,STER MFT,MFT Connect:Direct,STERLING C D STD ED SMLT SESSN SUPT,Subs & Supp,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# Convert 'Industry' to string type
sales_data['Industry'] = sales_data['Industry'].astype(str)

# Replace blank values with '99'
sales_data['Industry'].replace(['nan', ''], '99', inplace=True)

In [ ]:
# Remove rows with blank 'PA part description'
sales_data = sales_data.dropna(subset=['PA part description'])

In [ ]:
# Remove rows with the specified value in 'UT L30 - Segment' column
value_to_remove = 'Data Exchange Service Offering (Expert Labs Only)'
sales_data = sales_data[sales_data['UT L30 - Segment'] != value_to_remove]

In [ ]:
#Replace negative values with 0
sales_data[cols_to_replace] = sales_data[cols_to_replace].applymap(lambda x: 0 if x < 0 else x)

In [ ]:
# Preview the modified dataset to confirm the changes
sales_data.head()

,ZXG ID,Country,Industry,UT L30 - Segment,Family,Product name,PA part description,Rev type,20161,20162,...,20204,20211,20212,20213,20214,20221,20222,20223,20224,Grand Total
0,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,B2B INTEGRATOR AO GLOBAL HIGH AVAILABILITY MB ...,Transaction,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2503116.9
1,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,B2B INTEGRATOR AO GLOBAL HIGH AVAILABILITY MB ...,Subs & Supp,0.0,0.0,...,31322.7,31322.7,31322.7,31322.7,31322.7,31322.7,31322.7,31322.7,31322.7,407055.6
2,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,B2B INTEGRATOR AO GLOBAL HIGH AVAILABILITY MB ...,Subs & Supp,0.0,0.0,...,125298.9,125298.9,125298.9,125298.9,125298.9,125298.9,125298.9,125298.9,125298.9,1628306.1
3,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,STERLING B2B INTEGRATOR ENT ED PVU SUPT,Subs & Supp,2797.2,2797.2,...,22226.4,22226.4,22226.4,22307.4,22307.4,22307.4,22307.4,22307.4,22307.4,278391.6
4,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,STERLING B2B INTEGRATOR ENT ED PVU SUB,Subs & Supp,11188.8,11188.8,...,88911.0,88911.0,88911.0,89237.7,89237.7,89237.7,89237.7,89237.7,89237.7,1113647.4

In [ ]:
# Standardize the revenue data by replacing any value > 0 with 1, indicating a sale
# Columns representing the quarterly sales data are specified in cols_to_replace
sales_data[cols_to_replace] = sales_data[cols_to_replace].applymap(lambda x: 1 if x > 0 else 0)

# Preview the modified dataset to confirm the changes
sales_data.head()

,ZXG ID,Country,Industry,UT L30 - Segment,Family,Product name,PA part description,Rev type,20161,20162,...,20204,20211,20212,20213,20214,20221,20222,20223,20224,Grand Total
0,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,B2B INTEGRATOR AO GLOBAL HIGH AVAILABILITY MB ...,Transaction,0,0,...,0,0,0,0,0,0,0,0,0,1
1,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,B2B INTEGRATOR AO GLOBAL HIGH AVAILABILITY MB ...,Subs & Supp,0,0,...,1,1,1,1,1,1,1,1,1,1
2,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,B2B INTEGRATOR AO GLOBAL HIGH AVAILABILITY MB ...,Subs & Supp,0,0,...,1,1,1,1,1,1,1,1,1,1
3,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,STERLING B2B INTEGRATOR ENT ED PVU SUPT,Subs & Supp,1,1,...,1,1,1,1,1,1,1,1,1,1
4,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,STERLING B2B INTEGRATOR ENT ED PVU SUB,Subs & Supp,1,1,...,1,1,1,1,1,1,1,1,1,1

In [ ]:
# Exclude the following column for long format transformation
id_vars = ['ZXG ID', 'Country', 'Industry', 'UT L30 - Segment', 'Family', 'Product name', 'PA part description', 'Rev type']
value_vars = sales_data.columns.drop(id_vars + ['Grand Total']).tolist()

# Melt the DataFrame to long format
sales_data_long = pd.melt(sales_data, id_vars=id_vars, value_vars=value_vars, var_name='Quarter', value_name='Revenue')

# Keep only the specified quarters
#quarters_to_keep = ['20221','20222','20223','20224','20171','20172','20173','20174']
#sales_data_long = sales_data_long[sales_data_long['Quarter'].isin(quarters_to_keep)]

# Filter for 'Industry' = 1
#sales_data_long = sales_data_long[sales_data_long['Industry'] == '1.0']

# Keep only the rows where a sale occurred, i.e., 'Revenue' = 1
#sales_data_long = sales_data_long[sales_data_long['Revenue'] == 1]

# Keep only the rows where a Rev type = 'Subs and Supp'
#sales_data_long = sales_data_long[sales_data_long['Rev type'] == 'Subs and Supp']

# Keep only the rows where a Product name = 'MFT Connect:Direct'
#sales_data_long = sales_data_long[sales_data_long['Product name'] == 'MFT Connect:Direct']

# Keep only the rows for United States
#sales_data_long = sales_data_long[sales_data_long['Country'] == 'United States']

# Drop unnecessary columns, but retain 'Product name' for grouping
cols_to_drop = ['Country', 'Industry', 'UT L30 - Segment', 'Family', 'Rev type']
sales_data_long.drop(columns=cols_to_drop, inplace=True)

# Convert the quarter to datetime format
def quarter_to_datetime(quarter_str):
    year = quarter_str[:4]
    q = int(quarter_str[4])
    month = (q - 1) * 3 + 1  # Get the starting month of the quarter
    return f"{year}{month:02}"

sales_data_long['Quarter'] = sales_data_long['Quarter'].apply(quarter_to_datetime)
sales_data_long['Quarter'] = pd.to_datetime(sales_data_long['Quarter'], format='%Y%m')

# Sort the DataFrame by company, product name, and quarter
sales_data_long.sort_values(['ZXG ID', 'Product name', 'Quarter'], inplace=True)

# Reset the index
sales_data_long.reset_index(drop=True, inplace=True)

# Function to remove consecutive duplicates
def remove_consecutive_duplicates(seq):
    if not seq:
        return []

    result = [seq[0]]
    for item in seq[1:]:
        if item != result[-1]:
            result.append(item)
    return result

# Group by 'ZXG ID' and 'Product name' and then remove consecutive duplicates
grouped_sequences = sales_data_long.groupby(['ZXG ID', 'Product name','Quarter'])['PA part description'].apply(list)
grouped_sequences = grouped_sequences.apply(remove_consecutive_duplicates)

# Convert to a list of lists for the PrefixSpan algorithm
grouped_sequences_list = [list(group) for _, group in grouped_sequences.items()]

In [ ]:
# Preview the first 5 sequences (company-product transactions)
for i, sequence in enumerate(grouped_sequences_list[:5], 1):
    print(f"Sequence {i}:")
    print(sequence)
    print("-" * 50)  # Just a separator for clarity

Sequence 1:
['STERLING B2B INTEGRATOR ENT ED PVU INSTL', 'STERLING B2B INTEGRATOR ENT ED PVU SUPT', 'STERLING B2B INTEGRATOR ENT ED PVU SUB', 'STERLING B2B INTEGRATOR ENT ED NON-PROD ENV PVU SUPT', 'STERLING B2B INTEGRATOR ENT ED NON-PROD ENV PVU SUB', 'STERLING B2B INTEGRATOR STD ED CONNECTION INSTL', 'IBM STERLING B2B INTEGRATOR STANDARD EDITION CONNECTION LICENSE + SW SUBSCR', 'STERLING B2B INTEGRATOR STD ED CONNECTION SUPT', 'STERLING B2B INTEGRATOR STD ED CONNECTION SUB', 'STERLING B2B INTEGRATOR STD ED PVU INSTL', 'STERLING B2B INTEGRATOR STD ED PVU SUPT', 'STERLING B2B INTEGRATOR STD ED PVU SUB', 'STERLING B2B INTEGRATOR STD ED NON-PROD ENV PVU INSTL', 'STERLING B2B INTEGRATOR STD ED NON-PROD ENV PVU SUPT', 'STERLING B2B INTEGRATOR STD ED NON-PROD ENV PVU SUB', 'IBM STERLING B2B INTEGRATOR BASIC EDITION PVU INSTL', 'IBM STERLING B2B INTEGRATOR BASIC EDITION PVU SUPT', 'IBM STERLING B2B INTEGRATOR BASIC EDITION PVU SUB', 'IBM STR B2B INTEGRATOR BASIC ED FOR NP ENV PVU SUPT', 'IBM STR B2B INTEGRATOR BASIC ED FOR NP ENV PVU SUB', 'STR B2B INTEGRATOR ENTERPRISE ED PVU LNX ON SYSZ INSTL']
--------------------------------------------------
Sequence 2:
['STERLING B2B INTEGRATOR ENT ED PVU INSTL', 'STERLING B2B INTEGRATOR ENT ED PVU SUPT', 'STERLING B2B INTEGRATOR ENT ED PVU SUB', 'STERLING B2B INTEGRATOR ENT ED NON-PROD ENV PVU SUPT', 'STERLING B2B INTEGRATOR ENT ED NON-PROD ENV PVU SUB', 'STERLING B2B INTEGRATOR STD ED CONNECTION INSTL', 'IBM STERLING B2B INTEGRATOR STANDARD EDITION CONNECTION LICENSE + SW SUBSCR', 'STERLING B2B INTEGRATOR STD ED CONNECTION SUPT', 'STERLING B2B INTEGRATOR STD ED CONNECTION SUB', 'STERLING B2B INTEGRATOR STD ED PVU INSTL', 'STERLING B2B INTEGRATOR STD ED PVU SUPT', 'STERLING B2B INTEGRATOR STD ED PVU SUB', 'STERLING B2B INTEGRATOR STD ED NON-PROD ENV PVU INSTL', 'STERLING B2B INTEGRATOR STD ED NON-PROD ENV PVU SUPT', 'STERLING B2B INTEGRATOR STD ED NON-PROD ENV PVU SUB', 'IBM STERLING B2B INTEGRATOR BASIC EDITION PVU INSTL', 'IBM STERLING B2B INTEGRATOR BASIC EDITION PVU SUPT', 'IBM STERLING B2B INTEGRATOR BASIC EDITION PVU SUB', 'IBM STR B2B INTEGRATOR BASIC ED FOR NP ENV PVU SUPT', 'IBM STR B2B INTEGRATOR BASIC ED FOR NP ENV PVU SUB', 'STR B2B INTEGRATOR ENTERPRISE ED PVU LNX ON SYSZ INSTL']
--------------------------------------------------
Sequence 3:
['STERLING B2B INTEGRATOR ENT ED PVU INSTL', 'STERLING B2B INTEGRATOR ENT ED PVU SUPT', 'STERLING B2B INTEGRATOR ENT ED PVU SUB', 'STERLING B2B INTEGRATOR ENT ED NON-PROD ENV PVU SUPT', 'STERLING B2B INTEGRATOR ENT ED NON-PROD ENV PVU SUB', 'STERLING B2B INTEGRATOR STD ED CONNECTION INSTL', 'IBM STERLING B2B INTEGRATOR STANDARD EDITION CONNECTION LICENSE + SW SUBSCR', 'STERLING B2B INTEGRATOR STD ED CONNECTION SUPT', 'STERLING B2B INTEGRATOR STD ED CONNECTION SUB', 'STERLING B2B INTEGRATOR STD ED PVU INSTL', 'STERLING B2B INTEGRATOR STD ED PVU SUPT', 'STERLING B2B INTEGRATOR STD ED PVU SUB', 'STERLING B2B INTEGRATOR STD ED NON-PROD ENV PVU INSTL', 'STERLING B2B INTEGRATOR STD ED NON-PROD ENV PVU SUPT', 'STERLING B2B INTEGRATOR STD ED NON-PROD ENV PVU SUB', 'IBM STERLING B2B INTEGRATOR BASIC EDITION PVU INSTL', 'IBM STERLING B2B INTEGRATOR BASIC EDITION PVU SUPT', 'IBM STERLING B2B INTEGRATOR BASIC EDITION PVU SUB', 'IBM STR B2B INTEGRATOR BASIC ED FOR NP ENV PVU SUPT', 'IBM STR B2B INTEGRATOR BASIC ED FOR NP ENV PVU SUB', 'STR B2B INTEGRATOR ENTERPRISE ED PVU LNX ON SYSZ INSTL']
--------------------------------------------------
Sequence 4:
['STERLING B2B INTEGRATOR ENT ED PVU INSTL', 'STERLING B2B INTEGRATOR ENT ED PVU SUPT', 'STERLING B2B INTEGRATOR ENT ED PVU SUB', 'STERLING B2B INTEGRATOR ENT ED NON-PROD ENV PVU SUPT', 'STERLING B2B INTEGRATOR ENT ED NON-PROD ENV PVU SUB', 'STERLING B2B INTEGRATOR STD ED CONNECTION INSTL', 'IBM STERLING B2B INTEGRATOR STANDARD EDITION CONNECTION LICENSE + SW SUBSCR', 'STERLING B2B INTEGRATOR STD ED CONNECTION SUPT', 'STERLING B2B INTEGRATOR STD ED CONNECTION SUB', 'STERLING B2B INTEGRATOR STD ED PVU INSTL', 'STERLING B2B INTEGRATOR STD ED PVU SUPT', 'STERLING B2B INTEGRATOR STD ED PVU SUB', 'STERLING B2B INTEGRATOR STD ED NON-PROD ENV PVU INSTL', 'STERLING B2B INTEGRATOR STD ED NON-PROD ENV PVU SUPT', 'STERLING B2B INTEGRATOR STD ED NON-PROD ENV PVU SUB', 'IBM STERLING B2B INTEGRATOR BASIC EDITION PVU INSTL', 'IBM STERLING B2B INTEGRATOR BASIC EDITION PVU SUPT', 'IBM STERLING B2B INTEGRATOR BASIC EDITION PVU SUB', 'IBM STR B2B INTEGRATOR BASIC ED FOR NP ENV PVU SUPT', 'IBM STR B2B INTEGRATOR BASIC ED FOR NP ENV PVU SUB', 'STR B2B INTEGRATOR ENTERPRISE ED PVU LNX ON SYSZ INSTL']
--------------------------------------------------
Sequence 5:
['STERLING B2B INTEGRATOR ENT ED PVU INSTL', 'STERLING B2B INTEGRATOR ENT ED PVU SUPT', 'STERLING B2B INTEGRATOR ENT ED PVU SUB', 'STERLING B2B INTEGRATOR ENT ED NON-PROD ENV PVU SUPT', 'STERLING B2B INTEGRATOR ENT ED NON-PROD ENV PVU SUB', 'STERLING B2B INTEGRATOR STD ED CONNECTION INSTL', 'IBM STERLING B2B INTEGRATOR STANDARD EDITION CONNECTION LICENSE + SW SUBSCR', 'STERLING B2B INTEGRATOR STD ED CONNECTION SUPT', 'STERLING B2B INTEGRATOR STD ED CONNECTION SUB', 'STERLING B2B INTEGRATOR STD ED PVU INSTL', 'STERLING B2B INTEGRATOR STD ED PVU SUPT', 'STERLING B2B INTEGRATOR STD ED PVU SUB', 'STERLING B2B INTEGRATOR STD ED NON-PROD ENV PVU INSTL', 'STERLING B2B INTEGRATOR STD ED NON-PROD ENV PVU SUPT', 'STERLING B2B INTEGRATOR STD ED NON-PROD ENV PVU SUB', 'IBM STERLING B2B INTEGRATOR BASIC EDITION PVU INSTL', 'IBM STERLING B2B INTEGRATOR BASIC EDITION PVU SUPT', 'IBM STERLING B2B INTEGRATOR BASIC EDITION PVU SUB', 'IBM STR B2B INTEGRATOR BASIC ED FOR NP ENV PVU SUPT', 'IBM STR B2B INTEGRATOR BASIC ED FOR NP ENV PVU SUB', 'STR B2B INTEGRATOR ENTERPRISE ED PVU LNX ON SYSZ INSTL']
--------------------------------------------------

In [ ]:
#Export dataframe to csv file called 'Preprocessed_Data_For_Dashboard'
grouped_sequences.to_csv('Preprocessed_Data_For_Python_Script.csv')

In [ ]:
#Downlaod
from google.colab import files
files.download('Preprocessed_Data_For_Python_Script.csv')

In [ ]:
#pip install prefixspan
from prefixspan import PrefixSpan

In [ ]:
def top_three_before_and_after(product_name, sequences):
    preceding_products_count = {}
    subsequent_products_count = {}

    # Process sequences
    for seq in sequences:
        if product_name in seq:
            index = seq.index(product_name)

            # Check for preceding product
            if index > 0:
                preceding_product = seq[index - 1]
                preceding_products_count[preceding_product] = preceding_products_count.get(preceding_product, 0) + 1

            # Check for subsequent product
            if index + 1 < len(seq):
                subsequent_product = seq[index + 1]
                subsequent_products_count[subsequent_product] = subsequent_products_count.get(subsequent_product, 0) + 1

    # Sort and retrieve top three preceding and subsequent products
    top_three_preceding = sorted(preceding_products_count.items(), key=lambda x: x[1], reverse=True)[:3]
    top_three_subsequent = sorted(subsequent_products_count.items(), key=lambda x: x[1], reverse=True)[:3]

    # Display results
    print(f"For the product '{product_name}':")
    for product, frequency in top_three_preceding:
        print(f"Before buying, the product '{product}' was bought {frequency} times.")
    for product, frequency in top_three_subsequent:
        print(f"After buying, the product '{product}' was bought {frequency} times.")

# Usage
product_name_input = 'STERLING C D PREM ED PVU SUB'  # Change this to any product name of interest
top_three_before_and_after(product_name_input, grouped_sequences)

For the product 'STERLING C D PREM ED PVU SUB':
Before buying, the product 'STERLING C D PREM ED PVU SUPT' was bought 31752 times.
Before buying, the product 'STERLING C D PREM ED PVU INSTL' was bought 56 times.
Before buying, the product 'STERLING C D STD ED NON-PROD ENV SMLT SESSN SUB' was bought 28 times.
After buying, the product 'MFT Connect:Direct' was bought 8932 times.
After buying, the product 'STERLING C D STD ED SMLT SESSN SUPT' was bought 7616 times.
After buying, the product 'STERLING C D PREM ED NON-PROD ENV PVU INSTL' was bought 3528 times.

In [ ]:
from collections import Counter

def most_frequent_baskets(product_name, sequences, top_n=2):
    baskets_with_product = []

    # Find all sequences containing the product
    for seq in sequences:
        if product_name in seq:
            baskets_with_product.append(tuple(sorted(seq)))  # Sort to ensure each basket has a unique representation

    # Count the frequency of each unique basket
    basket_counter = Counter(baskets_with_product)

    # Sort baskets by frequency
    sorted_baskets = sorted(basket_counter.items(), key=lambda x: x[1], reverse=True)

    # Display the top_n most frequent baskets
    print(f"Top {top_n} most frequent baskets containing '{product_name}':")
    for basket, frequency in sorted_baskets[:top_n]:
        print(f"Basket {basket} appears {frequency} times.")

product_name_input = 'STERLING C D PREM ED PVU SUB'
most_frequent_baskets(product_name_input, grouped_sequences)

Top 2 most frequent baskets containing 'STERLING C D PREM ED PVU SUB':
Basket ('MFT Connect:Direct', 'STERLING C D PREM ED PVU SUB', 'STERLING C D PREM ED PVU SUPT') appears 4620 times.
Basket ('MFT Connect:Direct', 'STERLING C D PREM ED PVU INSTL', 'STERLING C D PREM ED PVU SUB', 'STERLING C D PREM ED PVU SUPT') appears 3500 times.

In [ ]:
ps = PrefixSpan(grouped_sequences_list)

# Set the minimum support threshold
min_support = 10  # Can adjust this based on our requirements
patterns = ps.frequent(min_support)

# 3. Display the patterns along with their frequencies
for pattern in patterns:
    frequency, grouped_sequences = pattern
    print(f"Frequency: {frequency}\nSequence: {grouped_sequences}\n")