In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

file_path = '/content/drive/MyDrive/IBM NEXT BEST SOLUTION/Sales 2016-2022 v6.xlsx'
sales_data = pd.read_excel(file_path)

In [ ]:
# Display the first few rows of the dataframe
sales_data.head()

,ZXG ID,Country,Industry,UT L30 - Segment,Family,Product name,PA part description,Rev type,20161,20162,...,20204,20211,20212,20213,20214,20221,20222,20223,20224,Grand Total
0,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,B2B INTEGRATOR AO GLOBAL HIGH AVAILABILITY MB ...,Transaction,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2503116.9
1,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,B2B INTEGRATOR AO GLOBAL HIGH AVAILABILITY MB ...,Subs & Supp,NaN,NaN,...,31322.7,31322.7,31322.7,31322.7,31322.7,31322.7,31322.7,31322.7,31322.7,407055.6
2,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,B2B INTEGRATOR AO GLOBAL HIGH AVAILABILITY MB ...,Subs & Supp,NaN,NaN,...,125298.9,125298.9,125298.9,125298.9,125298.9,125298.9,125298.9,125298.9,125298.9,1628306.1
3,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,STERLING B2B INTEGRATOR ENT ED PVU SUPT,Subs & Supp,2797.2,2797.2,...,22226.4,22226.4,22226.4,22307.4,22307.4,22307.4,22307.4,22307.4,22307.4,278391.6
4,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,STERLING B2B INTEGRATOR ENT ED PVU SUB,Subs & Supp,11188.8,11188.8,...,88911.0,88911.0,88911.0,89237.7,89237.7,89237.7,89237.7,89237.7,89237.7,1113647.4

In [ ]:
# Columns to replace NaN values
cols_to_replace = ['20161','20162','20163','20164','20171','20172','20173','20174','20181','20182','20183','20184','20191','20192','20193','20194','20201','20202','20203','20204','20211','20212','20213','20214','20221','20222','20223','20224', 'Grand Total']

# Convert column names to strings
sales_data.columns = sales_data.columns.astype(str)

# Replace NaN values with 0 in the specified columns
sales_data[cols_to_replace] = sales_data[cols_to_replace].fillna(0)

In [ ]:
# Display the first few rows of the DataFrame after replacing NaN values
sales_data.head()

,ZXG ID,Country,Industry,UT L30 - Segment,Family,Product name,PA part description,Rev type,20161,20162,...,20204,20211,20212,20213,20214,20221,20222,20223,20224,Grand Total
0,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,B2B INTEGRATOR AO GLOBAL HIGH AVAILABILITY MB ...,Transaction,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2503116.9
1,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,B2B INTEGRATOR AO GLOBAL HIGH AVAILABILITY MB ...,Subs & Supp,0.0,0.0,...,31322.7,31322.7,31322.7,31322.7,31322.7,31322.7,31322.7,31322.7,31322.7,407055.6
2,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,B2B INTEGRATOR AO GLOBAL HIGH AVAILABILITY MB ...,Subs & Supp,0.0,0.0,...,125298.9,125298.9,125298.9,125298.9,125298.9,125298.9,125298.9,125298.9,125298.9,1628306.1
3,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,STERLING B2B INTEGRATOR ENT ED PVU SUPT,Subs & Supp,2797.2,2797.2,...,22226.4,22226.4,22226.4,22307.4,22307.4,22307.4,22307.4,22307.4,22307.4,278391.6
4,ZX001H1N,United States,1.0,Sterling B2B Integration,STER FILEGWA,B2B Integrator,STERLING B2B INTEGRATOR ENT ED PVU SUB,Subs & Supp,11188.8,11188.8,...,88911.0,88911.0,88911.0,89237.7,89237.7,89237.7,89237.7,89237.7,89237.7,1113647.4

In [ ]:
from itertools import groupby
from operator import itemgetter

# Find the indices of the rows where 'ZXG ID' is blank
blank_indices = sales_data[sales_data['ZXG ID'].isna()].index.tolist()

# Function to convert list of indices to ranges
def indices_to_ranges(indices):
    """Convert a list of indices to ranges"""
    ranges = []
    for k, g in groupby(enumerate(indices), lambda i_x:i_x[0]-i_x[1]):
        consecutive_indices = list(map(itemgetter(1), g))
        if len(consecutive_indices) == 1:
            ranges.append(str(consecutive_indices[0]))
        else:
            ranges.append(f"{consecutive_indices[0]}-{consecutive_indices[-1]}")
    return ranges

# Convert indices to ranges
blank_ranges = indices_to_ranges(blank_indices)
blank_ranges

['5780-5983',
 '6934-7079',
 '14962-15053',
 '20712-20777',
 '20829-20894',
 '29617-29703',
 '32024-32037',
 '32457-32518',
 '34181-34244',
 '34336-34351',
 '35441-35469',
 '38015-38023',
 '38828-38863',
 '41792-41806',
 '45231-45242',
 '46720-46731',
 '47870-47892',
 '48807',
 '48845-48848',
 '49455-49460',
 '49750-49753',
 '50679-50682',
 '51716-51723',
 '51988-51989',
 '52631-52632',
 '53124-53131',
 '53478-53483',
 '53926-53927',
 '54800-54802',
 '54981-54986',
 '55271-55273',
 '55825-55833',
 '56040-56041',
 '56220-56234',
 '56259-56264',
 '57101-57106',
 '57619-57622',
 '57712-57718',
 '57978-57980',
 '58080-58084',
 '58099-58102',
 '58465-58468',
 '58534-58535',
 '59603-59612',
 '59629-59662',
 '59679-59682',
 '59796-59804',
 '59837-59841',
 '59861-59863',
 '59921-59926',
 '60635-60680',
 '60829-60843',
 '62275-62294',
 '62346-62404',
 '64314-64329',
 '65835-65845',
 '66261-66275',
 '68672-68682',
 '68894-68913',
 '69538-69546',
 '70467-70472',
 '70596-70624',
 '70767-70779',
 '71050-71056',
 '72543-72550',
 '73835-73840',
 '75724-75726',
 '75811-75818',
 '76582-76584',
 '77866-77867',
 '77980-77981',
 '78038-78039',
 '78418-78419',
 '78813-78814',
 '79455-79463',
 '79799-79804',
 '80011-80013',
 '80158',
 '80595',
 '80856',
 '81121-81122',
 '81356',
 '81889',
 '81986-81987',
 '82080-82081',
 '82150-82153',
 '82176',
 '82692',
 '82859-82865',
 '82883',
 '83105',
 '83594-83596',
 '84058-84059',
 '84330-84331',
 '84823-84826',
 '84960-84962',
 '85465-85466',
 '86396',
 '87608-87609',
 '88323',
 '89192-89194',
 '89222-89226',
 '89240',
 '89345-89346',
 '89348',
 '89362-89364',
 '89375-89379',
 '89474-89495',
 '89529-89538']

In [ ]:
# Find all the rows where 'Country' is blank
blank_rows_country = sales_data[sales_data['Country'].isna()].index.tolist()

# Apply function to get ranges
blank_ranges_country = indices_to_ranges(blank_rows_country)
blank_ranges_country

['6934-7079', '62275-62294']

In [ ]:
# Replace the blanks in the specified ranges with the specified values
sales_data.loc[6934:7079, 'Country'] = sales_data.loc[6934:7079, 'Country'].fillna('Moe_Country')
sales_data.loc[62275:62294, 'Country'] = sales_data.loc[62275:62294, 'Country'].fillna('Wanchi_Country')

# Check if the replacements were successful
sales_data.loc[6934:7079]['Country'].unique(), sales_data.loc[62275:62294]['Country'].unique()

(array(['Moe_Country'], dtype=object), array(['Wanchi_Country'], dtype=object))

In [ ]:
# Initialize a company counter
company_counter = 1

# Iterate over the blank ranges in the 'ZXG ID' column
for start, end in [(int(r.split('-')[0]), int(r.split('-')[1])) if '-' in r else (int(r), int(r)) for r in blank_ranges]:
    # Get the unique countries in the current range
    unique_countries = sales_data.loc[start:end, 'Country'].unique()

    # Iterate over the unique countries
    for country in unique_countries:
        # Get the indices for the current country within the current range
        indices = sales_data.loc[start:end][sales_data['Country'] == country].index

        # Assign the company name to the 'ZXG ID' column for the current indices
        sales_data.loc[indices, 'ZXG ID'] = f'MW{company_counter}'

        # Increment the company counter
        company_counter += 1

# Check the first few rows of the modified dataset
sales_data.loc[[5780,5983,6934,7079,14962,15053,59837,59838,59839,59840,59841], :]

<ipython-input-9-3b18650c5010>:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  indices = sales_data.loc[start:end][sales_data['Country'] == country].index

,ZXG ID,Country,Industry,UT L30 - Segment,Family,Product name,PA part description,Rev type,20161,20162,...,20204,20211,20212,20213,20214,20221,20222,20223,20224,Grand Total
5780,MW1,United States,NaN,Sterling Transformation Extender,STER TRANSX,WebSphere Transform Ext Com Svr,WEBSPHERE TRANSFORM EXTEND WITH COMMAND PVU INSTL,Transaction,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1395744.3
5983,MW1,United States,NaN,Sterling Partner Engagement Manager,PEM,Sterling Prtnr Engage Mgr Software,IBM STERL PRTNR ENGAGEMENT MGR STD CTNR ED RVU...,Transaction,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,23102.1,0.0,0.0,0.0,23102.1
6934,MW2,Moe_Country,NaN,Sterling Transformation Extender,STER TRANSX,WS Transfrm Ext Pk Design Studio,WEBSPHERE TRANSFORM EXTENDER DESIGN STU AUTHUS...,Subs & Supp,0.0,-14175.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7079,MW2,Moe_Country,NaN,Sterling Partner Engagement Manager,PEM,Sterling Prtnr Engage Mgr Software,IBM STERLING PARTNER ENG MNGR STD ED PER ENTIT...,Transaction,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14962,MW3,Germany,NaN,Sterling Managed File Transfer,STER MFT,MFT Connect:Direct,STERLING C D STD ED NON-PROD ENV SMLT SESSN SUPT,Subs & Supp,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,115.2
15053,MW3,Germany,NaN,Sterling Partner Engagement Manager,PEM,Sterling Prtnr Engage Mgr Software,IBM STERL PRTNR ENGAGEMENT MGR STD CTNR ED RVU...,Transaction,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,-122.4,0.0,0.0,0.0,-122.4
59837,MW48,Denmark,NaN,Sterling Managed File Transfer,STER MFT,MFT Connect:Direct,STERLING C D PREM ED PVU SUPT,Subs & Supp,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-32.4
59838,MW49,Czech Republic,NaN,Sterling Managed File Transfer,STER MFT,MFT Connect:Direct,STERLING C D STD ED NON-PROD ENV SMLT SESSN SUPT,Subs & Supp,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-10.8
59839,MW49,Czech Republic,NaN,Sterling Managed File Transfer,STER MFT,MFT Connect:Direct,STERLING C D STD ED SMLT SESSN SUPT,Subs & Supp,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-21.6
59840,MW50,Belarus,NaN,Sterling Managed File Transfer,STER MFT,MFT Connect:Direct,STERLING C D STD ED NON-PROD ENV SMLT SESSN SUPT,Subs & Supp,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-16.2
59841,MW50,Belarus,NaN,Sterling Managed File Transfer,STER MFT,MFT Connect:Direct,STERLING C D STD ED SMLT SESSN SUPT,Subs & Supp,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-32.4

In [ ]:
# Convert 'Industry' to string type
sales_data['Industry'] = sales_data['Industry'].astype(str)

# Replace blank values with '99'
sales_data['Industry'].replace(['nan', ''], '99', inplace=True)

In [ ]:
# Melt the dataset from wide format to long format
data_melted = sales_data.melt(id_vars=['ZXG ID', 'Country', 'Industry', 'UT L30 - Segment', 'Family', 'Product name', 'PA part description', 'Rev type', 'Grand Total'],
                        var_name='Quarter',
                        value_name='Revenue')

# Filter out rows where no purchase was made
data_melted = data_melted[data_melted['Revenue'] != 0]

# Create a new column 'Transaction' which combines 'ZXG ID' and 'Quarter' to represent a single transaction
data_melted['Transaction'] = data_melted['ZXG ID'] + '_' + data_melted['Quarter']

# Pivot the data so that each product becomes a column
data_pivoted = data_melted.pivot_table(index='Transaction', columns='Product name', values='Revenue', fill_value=0)

# Convert the revenue values to 1 (purchased) and 0 (not purchased)
data_pivoted = data_pivoted.applymap(lambda x: 1 if x > 0 else 0)

# Display the first few rows of the pivoted data
data_pivoted.head()

Product name,AVP B2B INTEGRATION,AVP B2B MFT,AVP B2B SERVICES,B2B COLLAB 22,B2B COLLABORATION ESS MGMT,B2B Gateway Pack,B2B Integrator,B2B Integrator FCT,B2B Integrator Financial,B2B Integrator Financial FCT,...,d Client Support Services,e Implementation Services,e Implementation ServicesFCT,f Connectivity Services,f Connectivity ServicesFCT,fasp Protocol Connect:Direct,g Community Services,h Miscellaneous Add On ComponentFCT,h Miscellaneous Add On Components,z Legacy onlyFCT
Transaction,,,,,,,,,,,,,,,,,,,,,
MW100_20161,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
MW100_20162,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
MW100_20163,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
MW100_20164,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
MW100_20172,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
pip install efficient_apriori

Collecting efficient_apriori
  Downloading efficient_apriori-2.0.3-py3-none-any.whl (14 kB)
Installing collected packages: efficient_apriori
Successfully installed efficient_apriori-2.0.3

In [ ]:
from efficient_apriori import apriori

# Convert the DataFrame to a list of lists for the apriori function
transactions = data_pivoted.values.tolist()

# Convert the lists to strings (the apriori function requires string inputs)
transactions = [[str(j) for j in i] for i in transactions]

# Run the apriori function and print the frequent itemsets and the rules
itemsets, rules = apriori(transactions, min_support=0.01,  min_confidence=0.5)

In [ ]:
# Sort the rules by confidence level in descending order and print them
rules.sort(key=lambda x: x.confidence, reverse=True)
for rule in rules:
    print(rule)

{1} -> {0} (conf: 1.000, supp: 0.996, lift: 1.000, conv: 0.000)
{0} -> {1} (conf: 0.996, supp: 0.996, lift: 1.000, conv: 1.000)

In [ ]:
for k, v in itemsets.items():
    print(f"{k}-itemsets:")
    for items, support in v.items():
        print(f"  {items} - {support}")

1-itemsets:
  ('0',) - 213297
  ('1',) - 212383
2-itemsets:
  ('0', '1') - 212383